### ISSUE TITLE
Error encountered while running tep-meets-lstm.ipynb

### ISSUE THREAD

**Issue by SLZWVICTOR** [gmxavier/TEP-meets-LSTM#1]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-cee4b6d79bbe> in <module>()
      5 train_accuracies = []
      6 
----> 7 X_ = np.append(X_train, X_test, axis=0)
      8 y_ = np.append(y_train, y_test, axis=0)
      9 

C:\ProgramData\Anaconda3\envs\python3.5\lib\site-packages\numpy\lib\function_base.py in append(arr, values, axis)
   5150         values = ravel(values)
   5151         axis = arr.ndim-1
-> 5152     return concatenate((arr, values), axis=axis)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by gmxavier** [comment]
I recommend you run the notebook using Colab. I've made some changes in order to make it easy. Sorry the delayed answer.
